---
- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker.io package
      command: sudo apt update -y

